# Generated by Django 6.0.1 on 2026-01-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FestivMartApp', '0002_product_seller_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternative to uploading: provide an image URL', max_length=500, null=True),
        ),
    ]
