# Generated by Django 6.0.1 on 2026-01-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FestivMartApp', '0003_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
