# Generated by Django 6.0.1 on 2026-01-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FestivMartApp', '0005_userprofile_savings_order_orderitem_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='savings',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
