# Generated by Django 6.0.1 on 2026-01-30 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FestivMartApp', '0007_cart_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='FestivMartApp.category'),
        ),
    ]
